JRuby doesn't support 'read_uint64' method. Replace it with equivalent
Here is an error in JRuby
NameError: undefined method 'read_uint64' for class 'FFI::MemoryPointer'
           alias_method at org/jruby/RubyModule.java:2671
  <class:MemoryPointer> at lib/systemd/ffi_size_t.rb:13
                  <top> at lib/systemd/ffi_size_t.rb:4
                require at org/jruby/RubyKernel.java:937
                 (root) at /nix/store/3rha5350dg0s5gsb1d7g2w80v3vy81gr-jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
                  <top> at /nix/store/3rha5350dg0s5gsb1d7g2w80v3vy81gr-jruby-9.0.5.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
                require at org/jruby/RubyKernel.java:937
                 (root) at /nix/store/hvr16ijf0r8c0lr7an7kg22lsmzkdvwg-systemd-journal/lib/systemd/journal.rb:13
                  <top> at test.rb:1